on:
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'resources/**'
      - 'tools/**'
  pull_request:
    paths:
      - 'docs/**'
      - 'resources/**'
      - 'tools/**'
name: documentation
jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 50
    - name: Run website_build.sh
      run: ./tools/ci/website_build.sh
      env:
        DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
